# CONFIGURAÇÃO BASE
spring.application.name=pawsmanager

# Para o Swagger gerar URLs com HTTPS em vez de HTTP
server.forward-headers-strategy=framework

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
springdoc.swagger-ui.persistAuthorization=true



# Porta do servidor
server.port=8080

# JPA/Hibernate
spring.jpa.properties.hibernate.format_sql=true

# Cache Redis
spring.cache.type=redis


# Actuator
management.endpoints.web.exposure.include=health,metrics

# Micrometer
management.metrics.cache.instrument-auto-configured=true
