#PROFILE produção

# Banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/pawsmanager_mysql}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:usuario}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:senha123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
