# CONFIGURAÇÃO BASE

spring.application.name=gestaopetapi

# Porta do servidor
server.port=8080

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cache Redis
spring.cache.type=redis

# Executar scripts SQL automaticamente (desabilitado em prod)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Profile ativo (padrão: dev)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Actuator
management.endpoints.web.exposure.include=health,metrics

# Micrometer
management.metrics.cache.instrument-auto-configured=true
