
# PROFILE desenvolvimento local

# Banco de dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logs
logging.level.root=INFO
logging.level.com.pawsmanager.api=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# DevTools
spring.devtools.restart.enabled=true

# Actuator
management.endpoint.health.show-details=always