#PROFILE de testes

#desabilita redis nos testes

spring.cache.type=NONE
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# Desabilitar scripts SQL nos testes
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false